BEGIN;

CREATE TABLE IF NOT EXISTS surface_signals_latest (
  target_id BIGINT PRIMARY KEY REFERENCES targets(id) ON DELETE CASCADE,
  has_auth BOOLEAN NOT NULL DEFAULT FALSE,
  has_openapi BOOLEAN NOT NULL DEFAULT FALSE,
  has_upload BOOLEAN NOT NULL DEFAULT FALSE,
  has_admin BOOLEAN NOT NULL DEFAULT FALSE,
  has_graphql BOOLEAN NOT NULL DEFAULT FALSE,
  confidence INT NOT NULL DEFAULT 0,
  reasons JSONB,
  first_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_seen_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMIT;
